import java.util.HashMap;   

public class PoW{
    //State Variables
    HashMap<String, Double> problems = new HashMap<String, Double>();   //HashMap to store string for problem and double for answer
    int q_index;  

    /* THE CONSTRUCTOR */
    public PoW(int q_index) {
        buildProblems();    //Calling function that builds the HashMap
        this.q_index = q_index; //q_index to decide which question to choose
    }

    /**
     * This function gets all the questions within the problems HashMap
     * @return returns the question based on the PoW's q_index
     */
    public String getQuestion(){
        String questions[] = problems.keySet().toArray();
        return questions[q_index - 1];
    }
    /**
     * This function uses the getQuestion() method to get the answer for the question at the q_index position
     * @return returns the existing answer for the given question
     */
    public String getAnswer(){
        return problems.get(getQuestion(q_index - 1]));
    }
    /**
     * This function assigns pre-written problems and answers into the problems HashMap
     */
    public void buildProblems(){    
        problems.put("What is 1 + 1?", 2);  //Problem 1
        problems.put("What is the area of a cube with a width of 1?", 1);  //Problem 2
        problems.put("Roughly how many languages are there in the world?", 6500);  //Problem 3
         //Problem 4
        problems.put("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n 
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.", 4613732); 
        //Problem 5
        problems.put("A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. \n
            Find the largest palindrome made from the product of two 3-digit numbers.", 906609);  
        
    }


}